project:
  type: website
  resources:
    - "graph_output.html"
    - "nodes/*.ipynb"

website:
  title: "KB"
  favicon: "logo.png"
  navbar:
    left:
      - href: index.ipynb
        text: Home
      - href: graph.ipynb
        text: "Graph"
    right:
      - icon: envelope
        href: mailto:shervin.rowhani@gmail.com
        aria-label: Email
      - icon: github
        href: https://github.com/rohanishervin
        aria-label: GitHub
format:
  html:
    theme: cosmo
    code-fold: true
    toc: true
