import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "id": "yaml-header",
   "metadata": {},
   "source": [
    "---\n",
    "date: \"2026-07-29\"\n",
    "date-modified: last-modified\n",
    "format:\n",
    "  html:\n",
    "    toc: true\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "sec-intro",
   "metadata": {},
   "source": [
    "# Augmented Dickey–Fuller (ADF) Test\n",
    "\n",
    "The **Augmented Dickey–Fuller (ADF) test** is a practical statistical test used to determine whether a [time series](autocorrelation-and-stationarity.ipynb) is **stationary** or **non-stationary** (contains a [unit root](autoregressive-models.ipynb#stationarity-of-arp)).\n",
    "\n",
    "---\n",
    "\n",
    "## 1\\. Test Structure: Hypotheses & Regression Model\n",
    "\n",
    "Before running the test, it is essential to understand the two competing hypotheses and the regression equation used by the test.\n",
    "\n",
    "::: {#def-adf-hypotheses}\n",
    "## Hypotheses of the ADF Test\n",
    "* **Null Hypothesis ($H_0$):** $\\beta = 0$. The time series has a **unit root** and is **non-stationary** (e.g., a random walk). Its mean and variance change over time.\n",
    "* **Alternative Hypothesis ($H_1$ or $H_a$):** $\\beta < 0$. The time series has no unit root and is **weakly stationary** (mean-reverting).\n",
    ":::\n",
    "\n",
    "::: {.callout-note}\n",
    "## Important Distinction: Weak vs. Strong Stationarity\n",
    "The ADF test specifically evaluates **Weak Stationarity** (also known as **Covariance Stationarity** or **Second-Order Stationarity**), **not** Strong (Strict) Stationarity:\n",
    "\n",
    "* **Weak Stationarity (Evaluated by ADF):** Requires only that the first two moments remain time-invariant:\n",
    "  1. Constant mean: $E[x_t] = \\mu$\n",
    "  2. Constant finite variance: $\\text{Var}(x_t) = \\sigma^2 < \\infty$\n",
    "  3. Autocovariance depends only on lag $k$: $\\text{Cov}(x_t, x_{t-k}) = \\gamma_k$\n",
    "* **Strong (Strict) Stationarity:** Requires the *entire joint probability distribution* of any set of observations $(x_{t_1}, \\dots, x_{t_n})$ to be invariant to time shifts. A series can be weakly stationary without being strongly stationary (e.g., if higher-order moments like skewness or kurtosis fluctuate while mean and variance remain constant).\n",
    ":::\n",
    "\n",
    "### 1.1\\. The ADF Regression Model\n",
    "\n",
    "The test estimates the following Ordinary Least Squares (OLS) regression on the first-differenced series $\\Delta x_t = x_t - x_{t-1}$:\n",
    "\n",
    "$$\n",
    "\\Delta x_t = c_t + \\beta x_{t-1} + \\sum_{i=1}^{p-1} \\gamma_i \\Delta x_{t-i} + e_t\n",
    "$$\n",
    "\n",
    "Where:\n",
    "* **$\\Delta x_t = x_t - x_{t-1}$**: The change in the time series at step $t$.\n",
    "* **$x_{t-1}$**: The lagged level of the time series. Its coefficient $\\beta$ is what we test ($H_0: \\beta = 0$ vs $H_1: \\beta < 0$).\n",
    "* **$\\sum_{i=1}^{p-1} \\gamma_i \\Delta x_{t-i}$**: Lagged difference terms included to remove autocorrelation from the error term $e_t$.\n",
    "* **$c_t$**: Deterministic trend specification:\n",
    "  * `nc` (No constant): $c_t = 0$\n",
    "  * `c` (Constant / Drift): $c_t = \\mu$\n",
    "  * `ct` (Constant + Linear Trend): $c_t = \\mu + \\omega t$\n",
    "\n",
    "::: {.callout-note}\n",
    "## What is the ADF Test Statistic?\n",
    "The **ADF Test Statistic** is simply the OLS $t$-statistic for the coefficient $\\hat{\\beta}$:\n",
    "$$\n",
    "\\text{ADF Statistic} = \\frac{\\hat{\\beta}}{\\text{SE}(\\hat{\\beta})}\n",
    "$$\n",
    "Because the alternative hypothesis tests if $\\beta < 0$, the ADF test is a **one-tailed test**. A **more negative** test statistic provides stronger evidence to reject $H_0$ in favor of weak stationarity.\n",
    ":::\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "sec-interpretation",
   "metadata": {},
   "source": [
    "## 2\\. Decision Rules & Interpretation\n",
    "\n",
    "To make a statistical decision, compare the calculated **ADF Test Statistic** against the **Critical Values**, or evaluate the reported **$p$-value**:\n",
    "\n",
    "::: {.callout-warning}\n",
    "## Decision Rules\n",
    "1. **$p$-value Criterion:** \n",
    "   * If $p\\text{-value} \\le 0.05 \\implies$ **Reject $H_0$** (Series is **Weakly Stationary**).\n",
    "   * If $p\\text{-value} > 0.05 \\implies$ **Fail to Reject $H_0$** (Series is **Non-Stationary**).\n",
    "2. **Critical Value Criterion:**\n",
    "   * If ADF Statistic is **more negative** than the Critical Value (e.g., Stat $= -3.5 < -2.87$) $\\implies$ **Reject $H_0$** (Weakly Stationary).\n",
    "   * If ADF Statistic is **less negative** than the Critical Value (e.g., Stat $= -1.2 > -2.87$) $\\implies$ **Fail to Reject $H_0$** (Non-Stationary).\n",
    ":::\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code-sample-data",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from statsmodels.tsa.stattools import adfuller\n",
    "\n",
    "# Set random seed for reproducibility\n",
    "np.random.seed(42)\n",
    "\n",
    "# Generate sample time series (T = 250 steps)\n",
    "T = 250\n",
    "innovations = np.random.normal(loc=0.0, scale=1.0, size=T)\n",
    "\n",
    "# Series 1: Non-Stationary Price Series (Random Walk)\n",
    "price_series = 100 + np.cumsum(innovations)\n",
    "\n",
    "# Series 2: Stationary Returns Series (White Noise / Mean-reverting)\n",
    "return_series = innovations\n",
    "\n",
    "# Plot sample time series\n",
    "fig, axes = plt.subplots(2, 1, figsize=(10, 6), sharex=True)\n",
    "\n",
    "axes[0].plot(price_series, color=\"tab:red\", lw=1.5, label=\"Price Series (Random Walk)\")\n",
    "axes[0].set_title(\"Non-Stationary Time Series (Price Level)\")\n",
    "axes[0].set_ylabel(\"Price\")\n",
    "axes[0].legend()\n",
    "axes[0].grid(True, linestyle=\"--\", alpha=0.5)\n",
    "\n",
    "axes[1].plot(return_series, color=\"tab:blue\", lw=1.5, label=\"Daily Returns\")\n",
    "axes[1].axhline(0, color=\"black\", linestyle=\":\", alpha=0.7)\n",
    "axes[1].set_title(\"Stationary Time Series (Daily Returns)\")\n",
    "axes[1].set_xlabel(\"Time Step (Days)\")\n",
    "axes[1].set_ylabel(\"Return\")\n",
    "axes[1].legend()\n",
    "axes[1].grid(True, linestyle=\"--\", alpha=0.5)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Run ADF Test on both series using statsmodels\n",
    "res_price = adfuller(price_series, autolag='AIC')\n",
    "res_return = adfuller(return_series, autolag='AIC')\n",
    "\n",
    "def print_adf_report(series_name, result):\n",
    "    print(\"=\" * 55)\n",
    "    print(f\" ADF TEST RESULTS: {series_name}\")\n",
    "    print(\"=\" * 55)\n",
    "    print(f\"  [0] ADF Statistic  : {result[0]:.4f}\")\n",
    "    print(f\"  [1] p-value        : {result[1]:.4f}\")\n",
    "    print(f\"  [2] Lags Used      : {result[2]}\")\n",
    "    print(f\"  [3] Observations   : {result[3]}\")\n",
    "    print(\"  [4] Critical Values:\")\n",
    "    for key, val in result[4].items():\n",
    "        print(f\"        {key:>4}        : {val:.4f}\")\n",
    "    print(f\"  [5] Max IC (AIC)   : {result[5]:.2f}\")\n",
    "    print(\"=\" * 55)\n",
    "    print()\n",
    "\n",
    "print_adf_report(\"Price Series (Non-Stationary)\", res_price)\n",
    "print_adf_report(\"Return Series (Stationary)\", res_return)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "sec-explanation-statsmodels",
   "metadata": {},
   "source": [
    "## 3\\. Step-by-Step Breakdown of `statsmodels` ADF Output\n",
    "\n",
    "Calling `adfuller(series)` in Python returns a tuple containing 6 key elements. Here is how to read and interpret each element:\n",
    "\n",
    "### 3.1\\. Output Fields Explained\n",
    "\n",
    "1. **`result[0]` – ADF Statistic**:\n",
    "   * **Price Series:** `-0.9575`. This value is **not** more negative than the 5% critical value (`-2.8732`). Thus, we cannot reject $H_0$.\n",
    "   * **Return Series:** `-15.7423`. This value is **far more negative** than the 1% critical value (`-3.4569`), giving clear evidence to reject $H_0$.\n",
    "\n",
    "2. **`result[1]` – $p$-value**:\n",
    "   * **Price Series:** `0.7684` ($76.84\\%$). Since $p > 0.05$, we fail to reject $H_0$ $\\implies$ **Non-stationary**.\n",
    "   * **Return Series:** `0.0000` ($< 0.0001$). Since $p < 0.05$, we reject $H_0$ $\\implies$ **Weakly Stationary**.\n",
    "\n",
    "3. **`result[2]` – Lags Used**:\n",
    "   * The number of lagged difference terms ($p-1$) automatically chosen by the information criterion (AIC) to clean up residual autocorrelation.\n",
    "\n",
    "4. **`result[3]` – Number of Observations**:\n",
    "   * The number of effective data points used in the regression ($T - \\text{lags} - 1$).\n",
    "\n",
    "5. **`result[4]` – Critical Values**:\n",
    "   * Cutoff thresholds simulated for 1%, 5%, and 10% significance levels:\n",
    "     * `1%`: $-3.4569$\n",
    "     * `5%`: $-2.8732$\n",
    "     * `10%`: $-2.5730$\n",
    "   * To reject $H_0$ at the 5% level, the ADF statistic must be $\\le -2.8732$.\n",
    "\n",
    "6. **`result[5]` – Max Information Criterion (icbest)**:\n",
    "   * The optimized Akaike Information Criterion (AIC) score for the selected model order.\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

target_path = "/home/shrpc/wm/kb/nodes/augmented-dickey-fuller-test.ipynb"
with open(target_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)

print(f"Successfully generated {target_path}")
